version: "3"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rpassword
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
