name: Deploy to Hosting
on:
  push:
    branches:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4" # Set the appropriate PHP version here

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: install ssh keys
        # check this thread to understand why its needed:
        # https://stackoverflow.com/a/70447517
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: get hosts
        run: |
          ssh-keyscan host

      - name: Deploy to Hosting
        run: |
          ssh -p ${{secrets.HOST_PORT}} ${{ secrets.HOST_USER }}@${{ secrets.HOST_IP }} "cd ${{ secrets.TARGET_DIRECTORY }} && git pull"
        env:
          HOST_USER: ${{ secrets.HOST_USER }}
          HOST_IP: ${{ secrets.HOST_IP }}
          HOST_PORT: ${{ secrets.HOST_PORT }}
          TARGET_DIRECTORY: ${{ secrets.TARGET_DIRECTORY }}
